export const GET_COUNTRY_DETAILS_INIT = "GET_COUNTRY_DETAILS_INIT";
export const GET_COUNTRY_DETAILS_SUCCESS = "GET_COUNTRY_DETAILS_SUCCESS";
export const GET_COUNTRY_DETAILS_FAILURE = "GET_COUNTRY_DETAILS_FAILURE";
