export const GET_CAPITAL_WEATHER_DETAILS_INIT =
  "GET_CAPITAL_WEATHER_DETAILS_INIT";
export const GET_CAPITAL_WEATHER_DETAILS_SUCCESS =
  "GET_CAPITAL_WEATHER_DETAILS_SUCCESS";
export const GET_CAPITAL_WEATHER_DETAILS_FAILURE =
  "GET_CAPITAL_WEATHER_DETAILS_FAILURE";
